### ISSUE TITLE
Can we add a page explaining the advantages of this router over for example https://github.com/go-chi/chi?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#10]
Can we add a page explaining the advantages of this router over for example https://github.com/go-chi/chi?

**Comment by frederikhors** [comment]
Why is chi so slow compared to Bun? This is really crazy!

**Comment by vmihailenco** [comment]
Well, it is slow in comparison with other routers, but practically you will not notice a difference unless you are serving tens of thousands pages per second. But people like benchmarks so I comply.

I would not switch if you don't need error handling or have lots of traffic :)

>Why is chi so slow compared to Bun?

No ideas...
