### ISSUE TITLE
Where is the docs project?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#16]
Where is the project for bunrouter docs? I would subscribe to any changes on it, please.

Why don't you put it in the docs folder of the project? Also for https://github.com/uptrace/bun.

**Comment by vmihailenco** [comment]
Documentation site uses a locally modified VuePress theme so I can't publish it without forking & publishing the theme first :shrug:

**Comment by frederikhors** [comment]
Is public now?

**Comment by vmihailenco** [comment]
No, the interest in watching docs is low but the maintenance cost is high...

**Comment by frederikhors** [comment]
Oh. I don't understand. I'm usually using https://app.github-file-watcher.com/ to subscribe to docs repos. It's really useful to stay up-to-date with news. Can I ask you gently again to rethink about this? I think this is useful also for you too having it on GitHub easy peasy.

**Comment by vmihailenco** [comment]
Should be available at https://github.com/go-bun/bunrouter-docs
