### ISSUE TITLE
Any performance difference using default, `.Compat()` or `.Verbose()`?

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#17]
Is there any difference in performances using `.Compat()` or `.Verbose()` instead of the default router?

**Comment by frederikhors** [comment]
I'm asking this because I'm using [gqlgen](https://github.com/99designs/gqlgen) and [this function](https://github.com/99designs/gqlgen/blob/master/graphql/handler/server.go#L31) to initialize the handler.

**Comment by vmihailenco** [comment]
The difference is `req.WithContext(ctx)` call to pass `bunrouter.Params`. Other routers do the same and it should not matter in practice.

`Verbose` does not have `req.WithContext(ctx)` call and is slightly faster.
