### ISSUE TITLE
301 status and ERR_TOO_MANY_REDIRECTS for static dir

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#20]
I have these dirs:

```
- static
  - index.html
  - js
    - main.js
```

and I'm using the code listed here: https://bunrouter.uptrace.dev/guide/serving-static-files.html#fs-sub.

Single file retrieving is working fine (eg. `static/js/main.js`).

The issue I'm having is when I try to open `static/`. I get in browser a 301 for `static/` to `static` and vice-versa and then `ERR_TOO_MANY_REDIRECTS` in Chrome.

Is this my fault?

**Comment by frederikhors** [comment]
You can verify this by changing this line in file-server example:

https://github.com/uptrace/bunrouter/blob/4026a11ba646b7110767dd4e547df028666fa6b5/example/file-server/main.go#L26

to

`router.GET("/*path", bunrouter.HTTPHandler(fileServer))`

**Comment by vmihailenco** [comment]
Please try v1.0.2 and the updated example.

**Comment by frederikhors** [comment]
> > panic: /*path already handles GET
> 
> I will fix this shortly.

I think it is ok without that first `GET` anyway. It's working good! And it is like `go-chi` works too.

**Comment by frederikhors** [comment]
If you think about it, we don't need two routes that handle the same calls:

1. `router.GET("/", ...)`

1. `router.GET("/*path", ...)`

This is redundant!

Only the latter is ok: `router.GET("/*path", ...)`.

I personally don't like writing `path` after the `*`.

**Comment by vmihailenco** [comment]
>This is redundant!

Okay, let's keep this behavior. I can imagine arguments against such routing too, but perhaps it is fine.

>I personally don't like writing path after the *.

That is is needed so you can retrieve the param via `req.Param("path")`.
