### ISSUE TITLE
Issue with SSE server "flusher, err := w.(http.Flusher)" error

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#31]
I'm trying to use the amazing https://github.com/r3labs/sse with bunrouter.

```go
func main() {
	sseHandler := newSSEHandler()

	router := bunrouter.New(
		bunrouter.WithMiddleware(reqlog.NewMiddleware(reqlog.WithEnabled(true))),
	)

	router.NewGroup("sse",
		bunrouter.WithGroup(func(group *bunrouter.Group) {
			group.GET("", sseHandler)
		}),
	)

	// Start server here...
}

func newSSEHandler() bunrouter.HandlerFunc {
	sseServer := sse.New()

	sseServer.CreateStream("test")

	return func(w http.ResponseWriter, r bunrouter.Request) error {
		sseServer.HTTPHandler(w, r.Request)

		return nil
	}
}
```

But when it starts it gives:

```
Streaming unsupported!
```

which comes from here: https://github.com/r3labs/sse/blob/11986ea9f6a2aa21c3a8237090fb95d8a72ca577/http.go#L19:

```go
func (s *Server) HTTPHandler(w http.ResponseWriter, r *http.Request) {
	flusher, err := w.(http.Flusher)
	if !err {
		http.Error(w, "Streaming unsupported!", http.StatusInternalServerError)
		return
	}

	// ...
```

Is this a problem with bunrouter?

How can I fix it?

**Comment by vmihailenco** [comment]
Most likely this is a problem with `reqlog` - try to disable it. I will see to improve reqlog later.

**Comment by frederikhors** [comment]
I didn't have time to try, I went back to using go-chi. But soon in a future project I will return to using bunrouter.

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/bunrouter/commit/938d70aa4743d3c1492af8421a3fff14df986fa0

**Comment by frederikhors** [comment]
It works, thanks!
