### ISSUE TITLE
SERIOUS, issues with CORS and OPTIONS calls

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#33]
Coming from `go-chi` I was using this code:

```go
func main() {
	r := chi.NewRouter()

	r.Use(newCorsMiddleware())

	r.Get("/", myHandler)
	r.Post("/", myHandler)

	http.ListenAndServe(":3000", r)
}

func newCorsMiddleware(corsOriginList []string) func(h http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return cors.New(cors.Options{
			AllowedOrigins:   corsOriginList,
			AllowCredentials: true,
		}).Handler(next)
	}
}
```

When I use it from browser (with a fetch method in javascript) and an OPTIONS call starts it works, I get `204 No Content` and all the right `Access-Control-Allow-.....` correctly.

With the same code but `bunrouter` instead of `go-chi` things are different:

```go
func main() {
	r := bunrouter.New(bunrouter.WithMiddleware(newCorsMiddleware(corsOriginList)))

	router.NewGroup("/",
		bunrouter.WithGroup(func(group *bunrouter.Group) {
			group.GET("", myHandler)
			group.POST("", myHandler)
			//group.OPTIONS("", myHandler)
		}),
	)

	http.ListenAndServe(":3000", r)
}

func newCorsMiddleware(corsOriginList []string) func(h http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return cors.New(cors.Options{
			AllowedOrigins:   corsOriginList,
			AllowCredentials: true,
		}).Handler(next)
	}
}
```

During the `OPTIONS` call I get the `405 Method Not Allowed` but all the right `Access-Control-Allow-.....` correctly.

In `go-chi` I don't need to use `router.Options()` because this is a problem that https://github.com/rs/cors handles, not me.

I think something is broken with bunrouter in this case, infact if I add a `group.OPTIONS("", myHandler)` the call works, but obviously this is wrong because I'm not directly handling `OPTIONS` calls.

**Comment by vmihailenco** [comment]
Thanks for the report. This should be fixed in v1.0.5 - see the updated [CORS](https://github.com/uptrace/bunrouter/tree/master/example/cors) example

**Comment by frederikhors** [comment]
Something has definitely changed after the fix and in fact it works for all API endpoints. But there is a new problem.

In one case instead of receiving 2xx code status, I am receiving 301 and consequently this error:

```
Access to fetch at 'http://localhost:3000/login?flow=8106fa49-72bc-4365-b85f-5f3fa05df1c1' from origin 'http://localhost:4000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.
```

```
Request URL: http://localhost:3000/login?flow=8106fa49-72bc-4365-b85f-5f3fa05df1c1
Request Method: OPTIONS
Status Code: 301 
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 0
Date: Mon, 08 Nov 2021 14:35:13 GMT
Location: /login/?flow=8106fa49-72bc-4365-b85f-5f3fa05df1c1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.9,en-US;q=0.8,en;q=0.7
Access-Control-Request-Headers: content-type
Access-Control-Request-Method: POST
Connection: keep-alive
Host: localhost:3000
Origin: http://localhost:4000
Referer: http://localhost:4000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```

This is not happening with the same code and `go-chi`.

**Comment by frederikhors** [comment]
I think the problem is here: https://github.com/uptrace/bunrouter/blob/b621373e5ed07d76ec548becf02df1add9253c0e/router.go#L125-L135

**Comment by frederikhors** [comment]
Please re-open this issue, @vmihailenco.

**Comment by vmihailenco** [comment]
That can happen if you've defined the route with a slash at the end: `/login/` instead of `/login`

**Comment by frederikhors** [comment]
Nope, I'm using the same code as with `go-chi`.

1. With `go-chi`:

```go
router.Group(func(r chi.Router) {
	r.Get("/login/*", loginServerReverseProxy)
	r.Post("/login/*", loginServerReverseProxy)
})
```

1. With `bunrouter`:

```go
router.NewGroup("/login/*path",
	bunrouter.WithGroup(func(group *bunrouter.Group) {
		group.GET("", loginServerReverseProxy)
		group.POST("", loginServerReverseProxy)
	}),
)
```

**Comment by vmihailenco** [comment]
Well, that's exactly a route with a slash at the end: `/login/` + whatever. Bun correctly redirects `/login` to `/login/`. This is documented at https://bunrouter.uptrace.dev/guide/getting-started.html#routing-rules .

You need to add another route `/login` if you want it to work.

**Comment by frederikhors** [comment]
Oh, I'm really having a hard time understanding what's going on right now.

**Comment by frederikhors** [comment]
I need to handle that proxy on that route. How to do that? With `go-chi` that code was enough. Why bunrouter needs to redirect `/login` to `/login/? And Why do I need another route?

**Comment by vmihailenco** [comment]
That is how it works. Example from https://bunrouter.uptrace.dev/guide/getting-started.html#routing-rules

```
Route: /static/*path

  /static          redirect to /static/
  /static/         match
  /static/foo      match
  /static/foo-bar  match
  /static/foo/bar  match
```

I will check what other routers do tomorrow, but current behavior is consistent with other routing rules.

**Comment by frederikhors** [comment]
Adding the other route as you said it works but I think this is a strange code to have in router:

I need to handle paths like these:

- GET http://localhost:3000/login/browser
- POST http://localhost:3000/login?flow=dff612d2-4d90-4fdf-bf71-973fa49a36c2

```go
router.NewGroup("/login/*path",
	bunrouter.WithGroup(func(group *bunrouter.Group) {
		group.GET("", loginServerReverseProxy)
		//group.POST("", loginServerReverseProxy)
	}),
)

router.NewGroup("/login/",
	bunrouter.WithGroup(func(group *bunrouter.Group) {
		//group.GET("", loginServerReverseProxy)
		group.POST("", loginServerReverseProxy)
	}),
)
```

**Comment by frederikhors** [comment]
> I will check what other routers do tomorrow

With `go-chi` I don't need other routes to handle this - very frequent - behavior.

**Comment by vmihailenco** [comment]
I've just checked and httprouter has the same behavior. And it can be useful if you want to handle `/login` and `/login/*foo` separately.

You can rewrite your example like this:

```go
router.NewGroup("/login",
	bunrouter.WithGroup(func(group *bunrouter.Group) {
                group.GET("/*user", loginServerReverseProxy)
		group.POST("", loginServerReverseProxy)
	}),
)
```

**Comment by frederikhors** [comment]
Ok. I don't know, I still have doubts about this behavior different from `go-chi`. But maybe I just have to get used to it. I close for now, if I need an opinion again I will disturb you. You are really kind. Thank you so much!

**Comment by frederikhors** [comment]
@vm sorry to bother you again on this.

I don't know how to write these routes:


```go
router.NewGroup("/upload",
  bunrouter.WithMiddleware(authMiddleware),
  bunrouter.WithGroup(func(group *bunrouter.Group) {
    group.GET("/presign/*options", signerHandler())
    if config.uploadEnabled {
      group.POST("/up", uploadHandler())
    }
  }),
)
```

Using a GET for http://localhost:3000/upload/presign?user=ok it gives a 301 status code.

Why?

**Comment by vmihailenco** [comment]
Please provide a full example that reproduces the problem. `/upload/presign/?user=ok` should work and I have similar code that works fine.

**Comment by frederikhors** [comment]
Yeah. Now I tried from Postman and it works. But from my javascript APP it doesn't.

If I use `GET` `http://localhost:3000/upload/presign` it works.

If I use `GET` `http://localhost:3000/upload/presign?user=ok` it doesn't.

**Comment by frederikhors** [comment]
I get

```
Request URL: http://localhost:3000/upload/presign?user=ok
Request Method: GET
Status Code: 301 
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 70
Content-Type: text/html; charset=utf-8
Date: Mon, 06 Dec 2021 12:16:36 GMT
Location: /upload/presign/?user=ok
```

CORS is working good for all the routes and within my JS app as well. No changes there.

Form where is coming that `301`?

**Comment by frederikhors** [comment]
I'm using this JS code:

```js
await fetch(`http://localhost:3000/upload/presign?user=ok`)
```

and this works instead:

```js
await fetch(`http://localhost:3000/upload/presign`)
```

**Comment by frederikhors** [comment]
I also tried this too without success:

```js
await fetch(`http://localhost:3000/upload/presign/?user=ok`)
```

**Comment by vmihailenco** [comment]
`http://localhost:3000/upload/presign` redirects to `http://localhost:3000/upload/presign/` probably loosing query args. You should only use the route with the slash in the end.

You can try curl to check what Go returns:

```
curl -v http://localhost:3000/upload/presign/?user=ok
```

**Comment by frederikhors** [comment]
With curl it works! Why?

**Comment by frederikhors** [comment]
With curl it works with and without slash at the end. With JS not! Why?

**Comment by frederikhors** [comment]
I don't know what I did (but really nothing) and now it works. I do not understand. Sorry to bother, really.
