### ISSUE TITLE
http: superfluous response.WriteHeader call

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#37]
I'm using bunrouter now and sometimes it appears this warning in logging:

```
http: superfluous response.WriteHeader call from github.com/uptrace/bunrouter/extra/reqlog.(*statusCodeRecorder).WriteHeader (middleware.go:121)
```

Why?

https://github.com/uptrace/bunrouter/blob/b621373e5ed07d76ec548becf02df1add9253c0e/extra/reqlog/middleware.go#L121

**Comment by frederikhors** [comment]
This appeared for some calls to/from the endpoint that manages the SSE (server-sent event) explained in the issue: https://github.com/uptrace/bunrouter/issues/31.

**Comment by frederikhors** [comment]
It appears when I delete cookies in browser and try to reload the page of my SPA, I get a 401 and on the server this appears.

The code for the authMiddleware is the below, maybe something wrong with this?

```go
func newAuthMiddleware(authAPI *auth.APIClient, sessionCookieName string) bunrouter.MiddlewareFunc {
	return func(next bunrouter.HandlerFunc) bunrouter.HandlerFunc {
		return func(w http.ResponseWriter, r bunrouter.Request) error {
			foundCookie, err := r.Cookie(sessionCookieName)
			if err != nil {
				http.Error(w, "", http.StatusUnauthorized)

				return fmt.Errorf("no session cookie found in request: %w", err)
			}

			session, err := authAPI.GetSession(sessionCookieName + "=" + foundCookie.Value)
			if err != nil {
				http.Error(w, "", http.StatusUnauthorized)

				return fmt.Errorf("unauthorized user or malformed session cookie: %w", err)
			}

			return next(w, r.WithContext(context.WithValue(r.Context(), sessionCtxKey, session)))
		}
	}
}
```

If I remove the line `http.Error(w, "", http.StatusUnauthorized)` the warning is not there anymore but I loose the indication of the `http.StatusUnauthorized`.

How to accomplish this?

**Comment by frederikhors** [comment]
This happens also if I use this line instead of that:

```go
w.WriteHeader(http.StatusUnauthorized)
```

**Comment by vmihailenco** [comment]
Your app calls `WriteHeader` twice:
1. first time when you call `http.Error(w, "", http.StatusUnauthorized)`
2. second time from your error handler

You should eliminate one of the calls, e.g. make your error handler to also write the status code - see [doc](https://bunrouter.uptrace.dev/guide/error-handling.html) for an example

**Comment by frederikhors** [comment]
I'm sorry. If I read your example on page https://bunrouter.uptrace.dev/guide/error-handling.html: 

```go
case HTTPError: // already a HTTPError
  w.WriteHeader(err.statusCode)
  _ = bunrouter.JSON(w, err)
```

Isn't this the same of what I'm doing below?

```go
if err != nil {
	w.WriteHeader(http.StatusUnauthorized)

	return fmt.Errorf("unauthorized user or malformed session cookie: %w", err)
}
```

**Comment by vmihailenco** [comment]
>Isn't this the same of what I'm doing below?

Maybe - you haven't shown your error handler. How do you handle `return fmt.Errorf("unauthorized user or malformed session cookie: %w", err)`?

It is best to handle errors and write header from a single place so you can ignore the error.

But I guess there can be a problem with this call [here](https://github.com/uptrace/bunrouter/blob/master/request.go#L44). BunRouter can probably handle this better - I will send a fix.

**Comment by frederikhors** [comment]
> you haven't shown your error handler

I don't have one. This is a very upper middleware in the stack. I think I don't need an error handler because the other endpoints doesn't have possibly errors. This is the only point where an error can happen.

**Comment by vmihailenco** [comment]
Then you return the error `return fmt.Errorf("unauthorized user or malformed session cookie: %w", err)` to nowhere. BunRouter does not handle it. `reqlog` middleware will log it for you, but that is it.

Please try v1.0.6.

**Comment by frederikhors** [comment]
It works now. Thanks. 

> Then you return the error `return fmt.Errorf("unauthorized user or malformed session cookie: %w", err)` to nowhere.

I'm fine like this because I don't really need anyone to handle it.
