### ISSUE TITLE
Router unexpectedly panics in some cases

### ISSUE THREAD

**Issue by Seldszar** [uptrace/bunrouter#40]
Consider the following program:
```go
package main

import (
	"net/http"

	"github.com/uptrace/bunrouter"
)

func main() {
	router := bunrouter.New()

	router.GET("/campaigns", func(w http.ResponseWriter, req bunrouter.Request) error {
		return nil
	})

	router.GET("/causes", func(w http.ResponseWriter, req bunrouter.Request) error {
		return nil
	})

	http.ListenAndServe(":3000", router)
}
```
When I try [http://localhost:3000/c](http://localhost:3000/c) or [http://localhost:3000/cam](http://localhost:3000/cam), I get a 404 error, normal so far. But for some reason, the router panics with [http://localhost:3000/ca](http://localhost:3000/ca), same for [http://localhost:3000](http://localhost:3000).

Is it intended?

**Comment by vmihailenco** [comment]
This is not intented and should be fixed shortly. Thanks for the report.
