### ISSUE TITLE
Panic on route handler

### ISSUE THREAD

**Issue by ilteoood** [uptrace/bunrouter#47]
Hi,
I'm trying to handle two endpoints: `/api/internal` and `/api/internal/*params`.

IMO these are 2 different path, so the router should not panic.

Btw, I think that you should return an error instead of panic: in my case I'm using the router as dynamic matcher, so the panic can be an unattended behaviour.

**Comment by vmihailenco** [comment]
You are right. Those are 2 different routes and your example should work.

**Comment by ilteoood** [comment]
@vmihailenco do you need a reproduction code, or the info provided are sufficient?

**Comment by vmihailenco** [comment]
It is enough - just not trivial to fix...

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/bunrouter/commit/88b4d3ea352c92fc7a87972fc95add8e7f99c328

**Comment by frederikhors** [comment]
With this change my project doesn't work anymore. And I can't understand why.

**Comment by frederikhors** [comment]
Is the docs updated?

**Comment by vmihailenco** [comment]
The only change in behavior that I know is that with these routes:

```
	router := New()
	router.GET("/*path", handler)
	router.GET("/static/*path", handler)
```

`/static` is no longer redirected to `/static/` and instead is served by `/*path`. That is not what users usually want, but it is a correct behavior.

There are no changes in the docs.

**Comment by frederikhors** [comment]
I had this code:

```go
router.NewGroup("/login",
  bunrouter.WithGroup(func(group *bunrouter.Group) {
    group.GET("/*path", bunrouter.HTTPHandler(authProxy))
    group.POST("", bunrouter.HTTPHandler(authProxy))
  }),
)
```

and now to make it work I have to use this:

```go
router.NewGroup("/login",
  bunrouter.WithGroup(func(group *bunrouter.Group) {
    group.GET("/*path", bunrouter.HTTPHandler(authProxy))
    group.POST("/*path", bunrouter.HTTPHandler(authProxy)) // <---- added /*path to POST
  }),
)
```

so I used this:

```go
router.NewGroup("/login/*path", // <----- changed this
  bunrouter.WithGroup(func(group *bunrouter.Group) {
    group.GET("", bunrouter.HTTPHandler(authProxy)) // <----- removed /*path from there
    group.POST("", bunrouter.HTTPHandler(authProxy)) // <-----  and here
  }),
)
```

Is it ok? Do you see issues with this?

**Comment by vmihailenco** [comment]
That looks okay. But perhaps all you wanted to do is:

```go
router.NewGroup("/login",
  bunrouter.WithGroup(func(group *bunrouter.Group) {
    group.GET("/*path", bunrouter.HTTPHandler(authProxy))
    group.POST("/", bunrouter.HTTPHandler(authProxy))
  }),
)
```

**Comment by frederikhors** [comment]
Yeah. It works. I don't know why but I have a hard time understanding these routes. I really don't know why. Thanks.
