### ISSUE TITLE
Bug: Route doesn't match if inside the url are present encoded characters

### ISSUE THREAD

**Issue by Danielecina** [uptrace/bunrouter#53]
## Current Bug
I tried to register an api but the bunRouter route doesn't match if inside the path are present encoded characters

registered route ->`/api/backend/projects/:projectId/branches/:branchName/files/:filePath`
called url -> `/api/backend/projects/project-id/branches/branch-id/files/config-extension%252Fcms-backend%252FcmsProperties.json`

I use the method bunrouter.New().Compat().handle() to register the route.

## Version used
v1.0.10

**Comment by vmihailenco** [comment]
First, please read https://github.com/golang/go/issues/3659 for some details.

My testing shows that BunRouter handles `config-extension%252Fcms-backend%252FcmsProperties.json` correctly, but refuses to accept `config-extension%252Fcms-backend%2FcmsProperties.json`. The difference is `%252F` vs `%2F`.

I've sent https://github.com/uptrace/bunrouter/pull/54 that should handle `%2F` too. Can you test the master branch before I release it?

**Comment by vmihailenco** [comment]
Also, you could change the route to `/api/backend/projects/:projectId/branches/:branchName/files/*filePath` and use more conventional URLs like `/api/backend/projects/project-id/branches/branch-id/files/config-extension/cms-backend/cmsProperties.json`.

**Comment by Danielecina** [comment]
> Also, you could change the route to `/api/backend/projects/:projectId/branches/:branchName/files/*filePath` 
Ok. i will try and update the conversation in 1 to 2 hours

> and use more conventional URLs like `/api/backend/projects/project-id/branches/branch-id/files/config-extension/cms-backend/cmsProperties.json`.
Yes. This is a good suggestion. Unfortunately I need to use them because they are used to retrieve files from a gitlab repository.

**Comment by Danielecina** [comment]
Yes. it works. I use the last commit as module and my test pass.

**Comment by vmihailenco** [comment]
Thanks for testing it. I will make a release soon.
