### ISSUE TITLE
splice isn't used when serving files

### ISSUE THREAD

**Issue by ghz-max** [uptrace/bunrouter#60]
## 💡 The feature or bug you are proposing
splice isn't used when serving static files.

## 📄 The description of the bug or the logic behind your proposal
I have a special use case where I need to serve files from a local http server. Golang has a special behavior when the destination writer is a https://pkg.go.dev/net#TCPConn.ReadFrom and your source is a "splice-able" reader, like a file or a socket on a Linux host.

Steps to reproduce:
1) Download a large enough file (few hundreds MiB) and store it in /home/dev/Downloads
2) Run a bunrouter app serving static files on port 8083
```
package main

import (
	"flag"
	"log"
	"net/http"

	"github.com/uptrace/bunrouter"
	"github.com/uptrace/bunrouter/extra/reqlog"
)

var (
	dir = flag.String("dir", "/home/dev/Downloads", "file directory")
)

func main() {
	flag.Parse()

	router := bunrouter.New(
		bunrouter.Use(reqlog.NewMiddleware(reqlog.WithVerbose(false))),
	)

	fileServer := http.FileServer(http.Dir(*dir))
	fileServer = http.StripPrefix("/static", fileServer)

	router.GET("/static/*path", bunrouter.HTTPHandler(fileServer))

	log.Println("listening on http://localhost:8083 - serving ", *dir)
	log.Println(http.ListenAndServe(":8083", router))
}
```

3) Run a net/http app running on port 8082
```
package main

import (
	"flag"
	"log"
	"net/http"
)

var (
	dir = flag.String("dir", "/home/dev/Downloads", "file directory")
)

func main() {
	flag.Parse()

	fs := http.FileServer(http.Dir(*dir))
	http.Handle("/static/", http.StripPrefix("/static", fs))

	log.Println("listening on http://localhost:8082 - serving ", *dir)
	log.Println(http.ListenAndServe(":8082", nil))
}
```

4) Use a http benchmark tool like wrk, ab or h2load
e.g. : 
- wrk -c 128 -t 16 "http://127.0.0.1:8082/static/my_big_file"
- wrk -c 128 -t 16 "http://127.0.0.1:8083/static/my_big_file"
5) Results on a 16 cores host with each core at 100%:
- bunrouter: 16GiB/s
- net/http: 44GiB/s

The whole point of using splice is to avoid unnecessary cpu cycle.

## 🚀 The expected result
bunrouter uses https://pkg.go.dev/net#TCPConn.ReadFrom which allow splice to be used.

**Comment by vmihailenco** [comment]
Try to remove `reqlog.NewMiddleware` - it wraps `http.ResponseWriter` to enable logging.

**Comment by ghz-max** [comment]
Thanks for the quick answer!

You are right, without reqlog middleware, the speed is as expected.

**Comment by vmihailenco** [comment]
I guess we could add a [similar wrapper](https://github.com/uptrace/bunrouter/blob/master/extra/reqlog/middleware.go#L117-L119) to expose `ReadFrom` in reqlog.
