### ISSUE TITLE
unable to upgrade reqlog.flusher to websocket websocket: response does not implement http.Hijacker using websocket

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#62]
I'm trying for the first time to use websockets (`github.com/gorilla/websocket`) with bunrouter.

I'm using

```go
bunRouterOptions := []bunrouter.Option{
  // some...
}

bunRouterOptions = append(bunRouterOptions, bunrouter.Use(reqlog.NewMiddleware(reqlog.WithVerbose(true))))

router.Use(gqlgenDataloadersMiddleware).WithGroup("/graphql", func(group *bunrouter.Group) {
  group.GET("", bunrouter.HTTPHandler(gqlgenHandler))
  group.POST("", bunrouter.HTTPHandler(gqlgenHandler))
})
```

but I'm having this error:

```
unable to upgrade reqlog.flusher to websocket websocket: response does not implement http.Hijacker:
http: superfluous response.WriteHeader call from github.com/uptrace/bunrouter/extra/reqlog.(*statusCodeRecorder).WriteHeader (middleware.go:134)
```

If I comment the `append reqlog.NewMiddleware` line it works.

**Comment by vmihailenco** [comment]
Looks like we need to add more wrappers like this for Hijack method - https://github.com/uptrace/bunrouter/blob/master/extra/reqlog/middleware.go#L137-L145. Could you send a PR?

**Comment by frederikhors** [comment]
I don't know how to start. 😢

**Comment by vmihailenco** [comment]
No problem, looks like httpsnoop already handles all this.

**Comment by frederikhors** [comment]
Do we have any news on the performances after this? Did you relaunch the benchmarks?

**Comment by vmihailenco** [comment]
If you worry about performance - don't use reqlog. It is for debugging purposes and all benchmarks are done without such plugins.
