### ISSUE TITLE
`unable to upgrade struct { httpsnoop.Unwrapper...` and `http: superfluous response.WriteHeader call`

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#65]
_Sorry to bother you again._

I updated to `bunrouter` and `reqlog` `1.0.14` and the websocket works.

But now if I reject origin it warns with:

```shell
http: superfluous response.WriteHeader call from github.com/uptrace/bunrouter/extra/reqlog.NewResponseWriter.func1.1 (middleware.go:120)

unable to upgrade struct { httpsnoop.Unwrapper; http.ResponseWriter; http.Flusher; http.CloseNotifier; http.Hijacker; io.ReaderFrom } to websocket websocket: request origin not allowed by Upgrader.CheckOrigin
```

the code is:

```go
func newHandler() *handler.Server {
	gqlgenServer := handler.New(gqlgen.NewExecutableSchema(gqlgen.Config{Resolvers: &resolvers}))

	gqlgenServer.AddTransport(transport.Websocket{
		KeepAlivePingInterval: 10 * time.Second,
		Upgrader: websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				return false // if true here it has no errors with 1.0.14
			},
		}},
	)

	gqlgenServer.AddTransport(transport.POST{})

	return gqlgenServer
}

gqlgenHandler := newHandler()

router.Use(authMiddleware).WithGroup("/graphql", func(group *bunrouter.Group) {
  group.POST("", bunrouter.HTTPHandler(gqlgenHandler))
})
```

**Why?**

**Comment by vmihailenco** [comment]
Does the warning go away if you remove reqlog middleware?

**Comment by frederikhors** [comment]
I removed `reqlog`, now it prints:

```
2022/04/16 10:43:25 unable to upgrade *http.response to websocket websocket: request origin not allowed by Upgrader.CheckOrigin:
2022/04/16 10:43:25 http: superfluous response.WriteHeader call from github.com/99designs/gqlgen/graphql/handler/transport.SendError (error.go:15)
```

I'm sure when I was using "chi" router I didn't have these messages. And I don't know if it's good or not. 😄

**Comment by vmihailenco** [comment]
The first message is pretty obvious if you fully read it.

The 2nd only is about duplicated `WriteHeader` calls. You probably should inspect your middlewares that generate responses and make sure they don't conflict with whatever gqlgen does.

**Comment by frederikhors** [comment]
Yeah but the issue with reqlog is still there, right?

**Comment by vmihailenco** [comment]
Why if removing does not change the behavuor?

**Comment by frederikhors** [comment]
It changes.

**With** `reqlog` enabled I get:

`http: superfluous response.WriteHeader call from github.com/uptrace/bunrouter/extra/reqlog.NewResponseWriter.func1.1 (middleware.go:120)`

which I think it means something `superfluous` is doing in it, nope?

**Comment by vmihailenco** [comment]
And without it you get 

```
http: superfluous response.WriteHeader call from github.com/99designs/gqlgen/graphql/handler/transport.SendError (error.go:15)
```

which I think means you have a bug somewhere.

**Comment by frederikhors** [comment]
I think the code from that line is:

https://github.com/99designs/gqlgen/blob/5a49764956ffb674df2c9bee19455bb1fd3407db/graphql/handler/transport/error.go#L14-L21.

In my small project I DON'T have any `response.WriteHeader`.

If I remove `reqlog` that warn indicates that someone else is using `response.WriteHeader`.

Now the questions:

1. is `response.WriteHeader` in that `gqlgen` project unuseful or
2. is somewhere in `bunrouter` a call `response.WriteHeader` unuseful? Is it possible?

**Comment by frederikhors** [comment]
I say it again, but not to make comparisons, ONLY to understand: using "chi" this warning is not there and maybe it is a bad thing.

Can we understand together so I do a PR on that (big) project?

**Comment by vmihailenco** [comment]
>In my small project I DON'T have any response.WriteHeader

WriteHeader is called implicity whenever you write something to `ResponseWriter`.

If you think there is an issue with BunRouter, please provide a reproducer.

**Comment by frederikhors** [comment]
Dear @vmihailenco I created a small repo for this annoying issue: https://github.com/frederikhors/iss-superfl-response-writeheader.

### Steps:

1. clone it with: `git clone https://github.com/frederikhors/iss-superfl-response-writeheader.git`

1. start it with: `go run .`

1. go to: `http://localhost:9999/playground`

1. paste this there:

    ```graphql
    subscription {
        todo {
            id
        }
    }
    ```

1. the message is in console:

    ```
    listening on http://localhost:9999

    unable to upgrade struct { httpsnoop.Unwrapper; http.ResponseWriter; http.Flusher; http.CloseNotifier; http.Hijacker; io.ReaderFrom } to websocket websocket: request origin not allowed by Upgrader.CheckOrigin:
    
    http: superfluous response.WriteHeader call from github.com/uptrace/bunrouter/extra/reqlog.NewResponseWriter.func1.1 (middleware.go:120)
    ```

1. if you change the code @ line 53 of `main.go` (`return true/false`) it works obviously.

Is this a gqlgen problem?

I need to understand before a new PR on them.

Thank you for your work, really.

**Comment by vmihailenco** [comment]
gqlgen tries to write response twice in order to handle the error:
- first time from /pkg/mod/github.com/gorilla/websocket@v1.5.0/server.go:153
- second time from /pkg/mod/github.com/99designs/gqlgen@v0.17.3/graphql/handler/transport/error.go:15

Looks like there is custom error handler that you can set to partially mitigate the issue:

```go
	srv.AddTransport(transport.Websocket{
		KeepAlivePingInterval: 10 * time.Second,
		Upgrader: websocket.Upgrader{
			CheckOrigin: func(r *http.Request) bool {
				// return true
				return false
			},
			Error: func(w http.ResponseWriter, r *http.Request, status int, reason error) {
				fmt.Println("got error", reason)
			},
		},
	})
```

There is a similar issue - https://github.com/99designs/gqlgen/issues/1328

Overall, this does not look like a problem with BunRouter. You should see the similar behavior with other routers.
