### ISSUE TITLE
handler for common 404 and method not found 

### ISSUE THREAD

**Issue by MarcelXia** [uptrace/bunrouter#66]
## 💡 The feature or bug you are proposing
Where can I find how to make a :
- common 404 handler?
- method not found handler?

**Comment by vmihailenco** [comment]
I've updated the [basic](https://github.com/uptrace/bunrouter/blob/master/example/basic/main.go#L18-L19) example and the [docs](https://bunrouter.uptrace.dev/guide/golang-router.html#not-found-handler).
