### ISSUE TITLE
How to set params and emulate request to controller (handlerfunc)

### ISSUE THREAD

**Issue by marcelloh** [uptrace/bunrouter#68]
## 💡 The feature or bug you are proposing

Normally I'll do :
```
	resp := httptest.NewRecorder()
	req := bunrouter.Request{}
	req.Request = &http.Request{}
```
and I will create params like this:
```
	params := httprouter.Params{}
	params = append(params, httprouter.Param{Key: "id", Value: "157"})
```
But I can't find a way to add those to the request. (this is my question)
because proviously (`github.com/julienschmidt/httprouter`) I used to do :
```
controller.GetOneRecord(resp, req, params)
```
but now the params are wrapped inside of the request.

**Comment by vmihailenco** [comment]
Did you see [Testing routes](https://bunrouter.uptrace.dev/guide/golang-router.html#testing-routes) in the docs?

**Comment by MarcelXia** [comment]
Yes, but that example is just a plain route without a param, and my question is about finding help for a test with param.
se where normally the code is like this example:
```
func handler(w http.ResponseWriter, req bunrouter.Request) error {
    params := req.Params()
    path := params.ByName("path")
    id, err := params.Int64("id")
}
```
I want to know how to test calling this from within a test  with a filled id, or path ....
(and I didn't find any example)

**Comment by vmihailenco** [comment]
But the route in the example has a param - it even shows how to retrieve and test it.

There is no way to explicitly build a map of params, because params are extracted directly from the URL path using the matched route. In theory, we could provide API like this:

```go
router := bunrouter.New()
router.GET("/user/:param", ...)

req := router.NewRequest(http.MethodGet, "/user/hello", nil)
```

That will create a request with `param = "hello"` and it is not any different from what I already demonstrated [here](https://bunrouter.uptrace.dev/guide/golang-router.html#testing-routes).

**Comment by MarcelXia** [comment]
Ok, perhaps I've expressed myself badly.
What I want is to test the call to a handler method, so for example the call to user/hello is handled by the 
func (mr *UserController) Hello(writer http.ResponseWriter, request bunrouter.Request) error {}
So a direct call to this without going all the way to an actual web-hit.

For that, I need to be able to give a request of type  bunrouter.Request that can have params.
(This is what I am looking for)

**Comment by vmihailenco** [comment]
>What I want is to test the call to a handler method

The link I've provided does exactly that. You call `ServeHTTPError` and the controller is called.

**Comment by MarcelXia** [comment]
I know it is in that way because the router must be configured to call it. But to me it looks like a detour to call a method.
If there is no other solution so "manipulate" the bunrouter.Request?

**Comment by MarcelXia** [comment]
I"m sorry, but you don't seem to understand me.
i I would call from a test my handler func (mr *UserController) Hello(writer http.ResponseWriter, request bunrouter.Request) error {}
What do I need to do to have a param inside the request?

And you say: well, my detour does that, which I know. But that's not what I ask? I ask how to do it directly.... :-(

**Comment by vmihailenco** [comment]
This is how [Params](https://github.com/uptrace/bunrouter/blob/master/request.go#L104-L108) look like. BunRouter simply does not have a map of params. Instead, the params are extracted from the URL on demand.

**Comment by MarcelXia** [comment]
I still see no answer if it can be done directly. (answer: No is also an answer)

**Comment by vmihailenco** [comment]
No, the only supported way is https://bunrouter.uptrace.dev/guide/golang-router.html#testing-routes
