### ISSUE TITLE
serving static files gives 404

### ISSUE THREAD

**Issue by marcelloh** [uptrace/bunrouter#70]
## 💡 The feature or bug you are proposing
I try to serve static files, but even my simplest static dir fails.

## 📄 The description of the bug or the logic behind your proposal
```
	rootDir := libFile.RootDir()
	dir := rootDir + "/website/css/"
	fileServer := http.FileServer(http.Dir(dir))
	router.GET("/css/*path", bunrouter.HTTPHandler(fileServer))

```
dir is :
"/Users/marcelloh/data/go-private/SailboatCompanion/website/css/"
(which is the correct location)

## 🚀 The expected result
not a 404 when I call /css/mycss.css

When I debug, I can see that the node /css (which is node 0) is overwritten by the node /country

**Comment by vmihailenco** [comment]
See
- https://github.com/uptrace/bunrouter/tree/master/example/file-server
- [Serving Static Files](https://bunrouter.uptrace.dev/guide/serving-static-files.html)

**Comment by marcelloh** [comment]
I did see the 2 pages. The only thing I have is by serving files from a filesystem instead of the embedded ones, right?
I don't use: fileServer := http.FileServer(http.FS(filesFS))
but I use.   :fileServer := http.FileServer(http.Dir(dir))
Can that cause the difference?

**Comment by vmihailenco** [comment]
Sounds plausible

**Comment by marcelloh** [comment]
Is there any example where static files are served from the filesystem?

**Comment by marcelloh** [comment]
Here is a failing example:
```
package main

import (
	"log"
	"net/http"
	"time"

	"github.com/uptrace/bunrouter"
)

func main() {
	// fileServer := http.FileServer(http.FS(filesFS))
	dir := http.Dir("./files")
	fileServer := http.FileServer(dir)

	router := bunrouter.New()

	router.GET("/files/*path", bunrouter.HTTPHandler(fileServer))

	srv := &http.Server{
		Addr:         ":80",
		WriteTimeout: time.Second * 10,
		ReadTimeout:  time.Second * 10,
		IdleTimeout:  time.Second * 10,
		Handler:      router,
	}

	err := startWebServer(srv)
	if err != nil {
		print("error:" + err.Error())
	}
}

func startWebServer(srv *http.Server) (err error) {
	var listenErr error

	println("webserver started")
	if listenErr = srv.ListenAndServe(); listenErr != http.ErrServerClosed {
		log.Println("webserver has an error")
	}

	if listenErr != http.ErrServerClosed {
		err = listenErr
	}

	return err
}

```

**Comment by vmihailenco** [comment]
It should be `router.GET("/files/*path", bunrouter.HTTPHandler(http.StripPrefix("/files/", fileServer)))`.

**Comment by MarcelXia** [comment]
hmmm. must have made a typo when I tried, thanks for your patience. (you made an old man happy)
