### ISSUE TITLE
Preffered / Recommended way of binding JSON objects

### ISSUE THREAD

**Issue by namanchikara** [uptrace/bunrouter#75]
## 💡 The feature or bug you are proposing
In GIN we have ginCtx.ShouldBindWith(&model, bindingForm), so I was wondering if we can do something similar with bunrouter.

## 📄 The description of the bug or the logic behind your proposal

Not a bug

## 🚀 The expected result

Say we have a struct:
```
type User struct {
        ID                  int       `json:"id"`
	FullName            string    `json:"full_name"`
}
```

and a POST request payload:
```
{
  'full_name': 'some name'
}
```

Now after binding JSON we should have a similar resulting struct:
```
User {id: nil, FullName: "some name"}
```

**Comment by vmihailenco** [comment]
You can just use `json` package directly:

```go
if err := json.NewDecoder(req.Body).Decode(&destStruct); err != nil {
    return err
}
```

I doubt that bunrouter should provide a helper like this.
