### ISSUE TITLE
go get github.com/uptrace/bunrouter not pulling in two folders.

### ISSUE THREAD

**Issue by eathom91** [uptrace/bunrouter#76]
## 💡 The feature or bug you are proposing
When running **go get github.com/uptrace/bunrouter** the example and extra folders are not being pulled in. 

I've ran the command in two separate work stations and both times extra and example folders were not included in the go get. I'm primarily trying to bring in the reqlog middleware from extra as per the documentation/getting started.

I don't have a proposed solution to this issue, but I wanted to see if there is a known reason behind this occuring. Any info would be great!

**Comment by eathom91** [comment]
User, error. Closing as resolved. Thanks.

**Comment by vmihailenco** [comment]
For others, extra modules should be installed separately `go get github.com/uptrace/bunrouter/extra/reqlog`
