### ISSUE TITLE
panic: routes "/x/*path" and "/x/" have different param names for the same route

### ISSUE THREAD

**Issue by frederikhors** [uptrace/bunrouter#81]
I have this code that works with `github.com/uptrace/bunrouter v1.0.17` and `github.com/uptrace/bunrouter/extra/reqlog v1.0.17`:

```go
reverseProxy := newReverseProxy(host)

router.WithGroup("/custom", func(group *bunrouter.Group) {
  group.GET("/*path", bunrouter.HTTPHandler(reverseProxy))
  group.POST("/", bunrouter.HTTPHandler(reverseProxy))
})
```

now after the update to `github.com/uptrace/bunrouter v1.0.18` and `github.com/uptrace/bunrouter/extra/reqlog v1.0.18` it panics with:

```
panic: routes "/custom/*path" and "/custom/" have different param names for the same route
```

**Why?**

What code should I use for this?

**Comment by vmihailenco** [comment]
Should be fixed by https://github.com/uptrace/bunrouter/commit/1a7449219a1d96e6808a243646266b1675380a4e

**Comment by frederikhors** [comment]
It works. Thanks.
