### ISSUE TITLE
router.WithGroup question

### ISSUE THREAD

**Issue by marcelloh** [uptrace/bunrouter#84]
## 💡 The feature or bug you are proposing
I have this code:
```
	router.WithGroup("/todo", func(group *bunrouter.Group) {
		group.GET("", mr.DebugHandler)
		group.GET("/:id", mr.DebugHandler)
		group.POST("/edit/:id", mr.DebugHandler)
	})
```
Which I think should be able to serve /todo/edit/9

## 📄 The description of the bug or the logic behind your proposal
My webserver shows me:
Page not found (/todo/edit/9) or method (GET) not allowed

## 🚀 The expected result
```
{"params":{"id":"9"},"route":"/todo/edit/:id"}
```
Am I doing something wrong here?

**Comment by vmihailenco** [comment]
>method (GET) not allowed

Your route uses `POST`, but here you have `GET`. Can it be the problem?

**Comment by marcelloh** [comment]
Hahahaha, see: I'm not fully awake but luckily you are.
It IS the problem, or rather: I was the problem.
Thanks for being that awake :-)
