### ISSUE TITLE
Mutual TLS with bun router

### ISSUE THREAD

**Issue by rvishureddy** [uptrace/bunrouter#87]
## 🚀 A way to do Mutual TLS 

        // Create a CA certificate pool and add cert.pem to it
        //root_ca.crt  server.crt  server.key
        caCert, err := ioutil.ReadFile(cfg.RootCert)
        if err != nil {
                log.Fatal(err)
        }
        caCertPool := x509.NewCertPool()
        caCertPool.AppendCertsFromPEM(caCert)

        // Create the TLS Config with the CA pool and enable Client certificate validation
        tlsConfig := &tls.Config{
                ClientCAs:  caCertPool,
                ClientAuth: tls.RequireAndVerifyClientCert,
        }
        tlsConfig.BuildNameToCertificate()

        // Create a Server instance to listen on port 8443 with the TLS config
        server := &http.Server{
                Addr:      ":8443",
                TLSConfig: tlsConfig,
        }

        // Listen to HTTPS connections with the server certificate and wait
        log.Fatal(server.ListenAndServeTLS(cfg.MyCert, cfg.MyKey))

How this can be done with bun router

**Comment by rvishureddy** [comment]
This is how i am doing it in the http.Server
        // Create a CA certificate pool and add cert.pem to it
        //root_ca.crt  server.crt  server.key
        caCert, err := ioutil.ReadFile(cfg.RootCert)
        if err != nil {
                log.Fatal(err)
        }
        caCertPool := x509.NewCertPool()
        caCertPool.AppendCertsFromPEM(caCert)

        // Create the TLS Config with the CA pool and enable Client certificate validation
        tlsConfig := &tls.Config{
                ClientCAs:  caCertPool,
                ClientAuth: tls.RequireAndVerifyClientCert,
        }
        tlsConfig.BuildNameToCertificate()

        // Create a Server instance to listen on port 8443 with the TLS config
        server := &http.Server{
                Addr:      ":8443",
                TLSConfig: tlsConfig,
        }

        // Listen to HTTPS connections with the server certificate and wait
        log.Fatal(server.ListenAndServeTLS(cfg.MyCert, cfg.MyKey))

How can this be done with bun router

**Comment by vmihailenco** [comment]
The same, just set the handler to Bun router:

```go
    server := &http.Server{
            Addr:      ":8443",
            TLSConfig: tlsConfig,
            Handler: router,
    }
```
