### ISSUE TITLE
Join benchmarking chart

### ISSUE THREAD

**Issue by wildfiremedia** [uptrace/bunrouter#9]
You probably interested in joining the chart
https://github.com/the-benchmarker/web-frameworks

**Comment by vmihailenco** [comment]
I've sent https://github.com/the-benchmarker/web-frameworks/pull/4805

**Comment by waghanza** [comment]
The gap will change when we will go on **production** @vmihailenco (will be explained by some hardware / network changes). 

I, however, can not say if this gap will favor `net/http` or `fasthttp`.

Btw, feel free to ping me, or create any https://github.com/the-benchmarker/web-frameworks/discussions for further details
